# Generated by Django 4.1.5 on 2024-06-14 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_autorizacion_aprobado_el_autorizacion_aprobado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='habilitar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='importe',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
