# Generated by Django 4.1.5 on 2024-06-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_solicitud_habilitar_alter_solicitud_importe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='habilitar',
            new_name='estado',
        ),
    ]
