# Generated by Django 4.1.5 on 2024-06-15 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_autorizacion_options_alter_autorizante_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='saldo',
        ),
    ]
