# Generated by Django 4.1.5 on 2024-06-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_remove_cuenta_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
